### PR TITLE
FIx typo in application tutorial

### PR DESCRIPTION
**Pull request by ajmeese7**
Comment was a little messed up, it's better now :)

Love the project so far, great work!

### CODE REVIEW

**Review by andersevenrud — CHANGES_REQUESTED** [review]
Change commit message to `FIx typo in application tutorial`

**Comment by ajmeese7** [comment]
Is that what you meant?

**Comment by andersevenrud** [comment]
You can use the amend feature in git to change the messages and do a force-push to update a PR.

I corrected this manually and merged the changes (so that it would only contain one single commit).

**Comment by ajmeese7** [comment]
Great, thanks for the info! Will try to do better on the other PR you requested this in :)

**Pull request merged**
